import type { Localized } from "@/lib/i18n/config";

export type Experience = {
  id: string;
  client: string;
  role: Localized;
  period: Localized;
  start: string;
  location?: string;
  freelance?: boolean;
  current?: boolean;
  summary: Localized;
  highlights: Localized<string[]>;
  stack: string[];
  featured?: boolean;
};

export const experiences: Experience[] = [
  {
    id: "solvay",
    client: "Solvay",
    role: { fr: "AWS Solution Architect", en: "AWS Solution Architect" },
    period: { fr: "Depuis novembre 2025", en: "Since November 2025" },
    start: "2025-11",
    current: true,
    featured: true,
    summary: {
      fr: "Pilotage des architectures AWS pour les applications et la Landing Zone du groupe.",
      en: "Leading AWS architectures for the group's applications and Landing Zone.",
    },
    highlights: {
      fr: [
        "Définition et design des solutions pour les applications et la Landing Zone Solvay",
        "Fourniture des High Level Designs pour les projets hébergés sur AWS, et review constante de la documentation",
        "Leadership de la plateforme AWS en coordination avec l'Infra Lead Architect, responsabilité des changes",
        "Collaboration et guidance des Infrastructure Cloud Engineers",
        "Apport d'idées pour augmenter la robustesse et la sécurité de la plateforme",
        "Collaboration avec l'équipe FinOps pour le contrôle et la réduction des coûts",
      ],
      en: [
        "Definition and design of solutions for Solvay applications and Landing Zone",
        "High Level Designs for AWS-hosted projects, with constant documentation review",
        "AWS platform leadership alongside the Infra Lead Architect, ownership of AWS changes",
        "Collaboration with and guidance of Infrastructure Cloud Engineers",
        "Proposals to increase platform robustness and security",
        "Collaboration with the FinOps team on cost control and reduction",
      ],
    },
    stack: ["AWS", "Azure", "Jenkins", "Terraform", "IAM", "EC2", "S3", "AWS Backup"],
  },
  {
    id: "galiceau-rag",
    client: "Galiceau",
    role: {
      fr: "AI Systems Architect — Plateforme RAG sécurisée",
      en: "AI Systems Architect — Secure RAG Platform",
    },
    period: { fr: "Depuis 2026", en: "Since 2026" },
    start: "2026-01",
    freelance: true,
    current: true,
    featured: true,
    summary: {
      fr: "Conception d'une plateforme RAG production-grade pour l'interrogation de documents d'entreprise, avec contrôle d'accès strict et auditabilité complète.",
      en: "Design of a production-grade RAG platform for querying enterprise documents, with strict access control and full auditability.",
    },
    highlights: {
      fr: [
        "Architecture end-to-end : ingestion, retrieval, génération, authentification, audit",
        "Vector search avec permissions appliquées au niveau du document",
        "Pipelines LLM avec token control, retry strategies et gestion de la concurrence",
        "Infrastructure AWS sécurisée : KMS BYOK, IAM least privilege, observabilité",
        "Property-based testing pour la validation des invariants système",
      ],
      en: [
        "End-to-end architecture: ingestion, retrieval, generation, authentication, audit",
        "Vector search with permissions enforced at document level",
        "LLM pipelines with token control, retry strategies and concurrency management",
        "Secure AWS infrastructure: KMS BYOK, IAM least privilege, observability",
        "Property-based testing to validate system invariants",
      ],
    },
    stack: [
      "Python (FastAPI, asyncio)",
      "Amazon Bedrock",
      "PostgreSQL pgvector",
      "ECS Fargate",
      "RDS",
      "KMS",
      "Cognito",
      "Terraform",
      "React/TypeScript",
    ],
  },
  {
    id: "galiceau-agentic",
    client: "Galiceau",
    role: {
      fr: "Agentic AI Systems Architect — Agent IA multi-plateformes",
      en: "Agentic AI Systems Architect — Multi-Platform AI Agent",
    },
    period: { fr: "Depuis 2026", en: "Since 2026" },
    start: "2026-01",
    freelance: true,
    current: true,
    featured: true,
    summary: {
      fr: "Design et développement d'un agent IA autonome de génération, évaluation et publication de contenu sur LinkedIn et X.",
      en: "Design and development of an autonomous AI agent generating, evaluating and publishing content on LinkedIn and X.",
    },
    highlights: {
      fr: [
        "Agent autonome end-to-end : generate / evaluate / decide / act",
        "Système de décision hybride : veto déterministe + LLM scoring",
        "Système de connaissance basé RAG pour l'enforcement du ton, du style et des contraintes",
        "Agent d'engagement autonome : feed scanning, reply generation, exécution de stratégie",
        "Contrôle human-in-the-loop maintenu via Telegram",
        "Optimisation sous contraintes : coût API, rate limits, scheduling",
      ],
      en: [
        "End-to-end autonomous agent: generate / evaluate / decide / act",
        "Hybrid decision system: deterministic veto + LLM scoring",
        "RAG-based knowledge system enforcing tone, style and constraints",
        "Autonomous engagement agent: feed scanning, reply generation, strategy execution",
        "Human-in-the-loop control maintained through Telegram",
        "Optimization under constraints: API cost, rate limits, scheduling",
      ],
    },
    stack: [
      "Amazon Bedrock",
      "Python",
      "Terraform",
      "EC2",
      "Lightsail",
      "S3",
      "IAM",
      "Hypothesis",
      "Telegram Bot API",
      "X API",
    ],
  },
  {
    id: "cegid",
    client: "Cegid",
    role: { fr: "AWS Architect & Lead DevOps", en: "AWS Architect & Lead DevOps" },
    period: { fr: "Octobre 2024 — Octobre 2025", en: "October 2024 — October 2025" },
    start: "2024-10",
    featured: true,
    summary: {
      fr: "Support de l'équipe Cloud dans l'implémentation de la plateforme AWS du groupe.",
      en: "Supporting the Cloud team in implementing the group's AWS platform.",
    },
    highlights: {
      fr: [
        "Tech Lead et Consult Advisor sur les sujets AWS et DevOps",
        "Design et implémentation de la AWS Landing Zone",
        "Support de la migration des applications Cegid vers AWS",
        "Design et implémentation des chaînes CI/CD pour les pipelines AWS dédiés",
        "Support FinOps : Saving Plans, BYOL, optimisation de la data consumption",
      ],
      en: [
        "Tech Lead and consulting advisor on AWS and DevOps topics",
        "Design and implementation of the AWS Landing Zone",
        "Support for migrating Cegid applications to AWS",
        "Design and implementation of CI/CD chains for dedicated AWS pipelines",
        "FinOps support: Saving Plans, BYOL, data consumption optimization",
      ],
    },
    stack: [
      "Terraform",
      "AWS Cloud WAN",
      "Transit Gateway",
      "Direct Connect",
      "IAM",
      "Checkpoint Firewall",
      "Azure DevOps",
      "JFrog",
      "Dynatrace",
    ],
  },
  {
    id: "bpifrance",
    client: "BPiFrance",
    role: { fr: "AWS Security Architect", en: "AWS Security Architect" },
    period: { fr: "Juillet 2025 — Septembre 2025", en: "July 2025 — September 2025" },
    start: "2025-07",
    freelance: true,
    summary: {
      fr: "Audit de sécurité cloud et remédiation de la plateforme Nanolike.",
      en: "Cloud security audit and remediation of the Nanolike platform.",
    },
    highlights: {
      fr: [
        "Conduite d'un audit de sécurité complet de la plateforme",
        "Identification et catégorisation des déficiences de sécurité à haut risque",
        "Développement d'un plan de remédiation détaillé",
        "Support FinOps pour l'optimisation des coûts",
      ],
      en: [
        "Comprehensive security audit of the platform",
        "Identification and categorization of high-risk security deficiencies",
        "Development of a detailed remediation plan",
        "FinOps support for cost optimization",
      ],
    },
    stack: ["AWS", "Azure", "Jenkins", "Terraform"],
  },
  {
    id: "teamlogs",
    client: "TeamLogs",
    role: { fr: "AWS Security Architect", en: "AWS Security Architect" },
    period: { fr: "Juin 2025 — Juillet 2025", en: "June 2025 — July 2025" },
    start: "2025-06",
    freelance: true,
    summary: {
      fr: "Audit de sécurité cloud et remédiation.",
      en: "Cloud security audit and remediation.",
    },
    highlights: {
      fr: [
        "Conduite d'un audit de sécurité complet",
        "Identification et catégorisation des déficiences de sécurité à haut risque",
        "Développement d'un plan de remédiation détaillé",
      ],
      en: [
        "Comprehensive security audit",
        "Identification and categorization of high-risk security deficiencies",
        "Development of a detailed remediation plan",
      ],
    },
    stack: ["AWS", "EC2", "IAM", "IoT", "API Gateway", "S3", "ALB/NLB", "Lambda"],
  },
  {
    id: "moodwork",
    client: "MoodWork",
    role: { fr: "AWS Solution Architect", en: "AWS Solution Architect" },
    period: { fr: "Janvier 2025 — Mai 2025", en: "January 2025 — May 2025" },
    start: "2025-01",
    freelance: true,
    summary: {
      fr: "Implémentation d'une stratégie de ségrégation de données robuste et renforcement de la posture de sécurité.",
      en: "Implementation of a robust data segregation strategy and hardening of the security posture.",
    },
    highlights: {
      fr: [
        "Leadership de l'implémentation d'une stratégie robuste de ségrégation de données",
        "Design et implémentation du chiffrement de données au niveau applicatif",
        "Review critique de la plateforme EKS et recommandations d'architecture",
        "Amélioration de la posture de sécurité de la plateforme",
      ],
      en: [
        "Led the implementation of a robust data segregation strategy",
        "Design and implementation of application-level data encryption",
        "Critical review of the EKS platform with architecture recommendations",
        "Improvement of the platform's security posture",
      ],
    },
    stack: ["AWS", "EKS", "KMS", "Kubernetes", "Terraform", "Java"],
  },
  {
    id: "smeg",
    client: "Smeg",
    role: { fr: "AWS Solution Architect", en: "AWS Solution Architect" },
    period: { fr: "Février 2023 — Août 2024", en: "February 2023 — August 2024" },
    start: "2023-02",
    location: "Monaco",
    freelance: true,
    summary: {
      fr: "Construction et amélioration de la plateforme AWS aux côtés de l'équipe Infrastructure.",
      en: "Building and improving the AWS platform alongside the Infrastructure team.",
    },
    highlights: {
      fr: [
        "Design et implémentation de la Landing Zone : IAM, VPN, Transit Gateway, Config Rules, sécurité",
        "Design de patterns EKS/RDS pour l'hébergement des applications",
        "Solution VDI pour les DevOps basée sur AWS Workspaces",
        "Stratégie de sécurisation de tous les endpoints publics : WAF, CloudFront, Web ACL, ALB, API Gateway",
        "Private Certification Authority (AWS PCA) et Private Hosting Zone",
        "Architecture GitLab résiliente et scalable, adoption de l'IaC, stratégie de backup/restore",
      ],
      en: [
        "Design and implementation of the Landing Zone: IAM, VPN, Transit Gateway, Config Rules, security",
        "EKS/RDS patterns for application hosting",
        "VDI solution for DevOps teams based on AWS Workspaces",
        "Security strategy for all public endpoints: WAF, CloudFront, Web ACL, ALB, API Gateway",
        "Private Certification Authority (AWS PCA) and Private Hosting Zone",
        "Resilient and scalable GitLab architecture, IaC adoption, backup/restore strategy",
      ],
    },
    stack: [
      "AWS",
      "Transit Gateway",
      "VPC",
      "IAM",
      "EKS",
      "EC2",
      "RDS",
      "S3",
      "AWS Backup",
      "Kubernetes",
      "Workspaces",
      "Terraform",
    ],
  },
  {
    id: "monaco-government",
    client: "Monaco Government",
    role: { fr: "AWS Solution Architect", en: "AWS Solution Architect" },
    period: { fr: "Mai 2022 — Février 2024", en: "May 2022 — February 2024" },
    start: "2022-05",
    location: "Monaco",
    freelance: true,
    featured: true,
    summary: {
      fr: "Définition, design et déploiement d'une Data Platform souveraine pour le Gouvernement de Monaco.",
      en: "Definition, design and deployment of a sovereign Data Platform for the Government of Monaco.",
    },
    highlights: {
      fr: [
        "Landing Zone de la Data Platform : identity baseline, Transit Gateway, Site-to-Site VPN, Client VPN",
        "Architecture Terraform Enterprise et Vault Enterprise",
        "Architecture Keycloak pour l'intégration SSO (SAML & OIDC) entre toutes les applications cœur",
        "Public Key Infrastructure basée sur Vault",
      ],
      en: [
        "Data Platform Landing Zone: identity baseline, Transit Gateway, Site-to-Site VPN, Client VPN",
        "Terraform Enterprise and Vault Enterprise architecture",
        "Keycloak architecture for SSO integration (SAML & OIDC) across all core applications",
        "Vault-based Public Key Infrastructure",
      ],
    },
    stack: [
      "AWS EC2",
      "RDS",
      "Route 53",
      "ACM",
      "KMS",
      "ECS",
      "Terraform",
      "Vault",
      "GitLab",
      "Keycloak",
      "SSO",
    ],
  },
  {
    id: "vallourec",
    client: "Vallourec",
    role: { fr: "FinOps Architect", en: "FinOps Architect" },
    period: { fr: "Mai 2022 — Juillet 2022", en: "May 2022 — July 2022" },
    start: "2022-05",
    location: "Valenciennes",
    freelance: true,
    summary: {
      fr: "Évaluation des coûts et usages AWS pour les entités Brésil et US.",
      en: "AWS cost and usage assessment for the Brazil and US entities.",
    },
    highlights: {
      fr: [
        "AWS Cost and Usage Assessment pour le Brésil et les États-Unis",
        "Évaluation des applications Vallourec hébergées sur AWS",
        "Élaboration du plan d'optimisation des usages AWS",
      ],
      en: [
        "AWS Cost and Usage Assessment for Brazil and the United States",
        "Assessment of Vallourec applications hosted on AWS",
        "Development of the AWS usage optimization plan",
      ],
    },
    stack: ["AWS", "Cost Explorer", "FinOps"],
  },
  {
    id: "safran-cabin",
    client: "Safran Cabin",
    role: { fr: "Data Platform Solution Architect", en: "Data Platform Solution Architect" },
    period: { fr: "Janvier 2022 — Avril 2022", en: "January 2022 — April 2022" },
    start: "2022-01",
    location: "Colomiers",
    freelance: true,
    summary: {
      fr: "Support de Safran Cabin et Safran Group pour la construction de leurs Data Platforms sur AWS.",
      en: "Supporting Safran Cabin and Safran Group in building their AWS Data Platforms.",
    },
    highlights: {
      fr: [
        "Accompagnement à la construction des Data Platforms Safran Cabin et Safran Group sur AWS",
      ],
      en: ["Support for building the Safran Cabin and Safran Group Data Platforms on AWS"],
    },
    stack: ["AWS"],
  },
  {
    id: "airbus-cles",
    client: "Airbus",
    role: { fr: "AWS Solution Architect — CLES", en: "AWS Solution Architect — CLES" },
    period: { fr: "Octobre 2021 — Décembre 2021", en: "October 2021 — December 2021" },
    start: "2021-10",
    location: "Toulouse",
    freelance: true,
    summary: {
      fr: "Développement du Customer Line Execution System (CLES) et de son pipeline de données.",
      en: "Development of the Customer Line Execution System (CLES) and its data pipeline.",
    },
    highlights: {
      fr: [
        "Développement du système CLES et du building pipeline pour le CLES Dataset dans Skywise",
        "Design du modèle de données CLES",
        "PoC d'un ingestion pipeline entre la plateforme Skywise (Foundry) et l'application CLES sur AWS",
      ],
      en: [
        "Development of the CLES system and the CLES Dataset building pipeline in Skywise",
        "Design of the CLES data model",
        "PoC of an ingestion pipeline between the Skywise (Foundry) platform and the AWS-based CLES application",
      ],
    },
    stack: [
      "AWS Glue",
      "S3",
      "IAM",
      "RDS",
      "CloudWatch",
      "EventBridge",
      "Lambda",
      "SQS",
      "Terraform",
      "Python",
      "Foundry",
    ],
  },
  {
    id: "monaco-digital",
    client: "Monaco Digital",
    role: { fr: "AWS Solution Architect", en: "AWS Solution Architect" },
    period: { fr: "Janvier 2021 — Novembre 2021", en: "January 2021 — November 2021" },
    start: "2021-01",
    location: "Monaco",
    freelance: true,
    summary: {
      fr: "Cloud souverain pour le Gouvernement de Monaco et ses Opérateurs d'Importance Vitale.",
      en: "Sovereign cloud for the Government of Monaco and its critical infrastructure operators.",
    },
    highlights: {
      fr: [
        "Définition, design, implémentation et déploiement du cloud souverain",
        "PoC de Cloud Management Platform et de solution de monitoring",
        "Landing Zone client et core foundation de l'infrastructure d'hébergement",
        "Monitoring solution pour le Core Operator et la hosting zone des clients",
        "Solution PKI pour la gestion des autorités de certification internes",
        "PoC de fédération d'identités entre AWS IAM et VMware Identity Manager (Workspace ONE Access)",
      ],
      en: [
        "Definition, design, implementation and deployment of the sovereign cloud",
        "PoC of a Cloud Management Platform and monitoring solution",
        "Customer Landing Zone and core foundation of the hosting infrastructure",
        "Monitoring solution for the Core Operator and customer hosting zone",
        "PKI solution to manage internal certificate authorities",
        "PoC of identity federation between AWS IAM and VMware Identity Manager (Workspace ONE Access)",
      ],
    },
    stack: [
      "AWS Outposts",
      "Organizations",
      "Config Rules",
      "EKS",
      "ECS",
      "SSO",
      "RDS",
      "Kinesis",
      "Terraform Enterprise",
      "Vault",
      "CloudBolt",
      "Ansible",
      "Grafana",
      "InfluxDB",
      "Prometheus",
    ],
  },
  {
    id: "roche",
    client: "Roche Diagnostics",
    role: { fr: "AWS Solution Architect", en: "AWS Solution Architect" },
    period: { fr: "Octobre 2020 — Mars 2021", en: "October 2020 — March 2021" },
    start: "2020-10",
    location: "Lyon",
    freelance: true,
    summary: {
      fr: "Design de la solution META1 à partir du PoC et alignement sur le Roche Security Standard.",
      en: "Design of the META1 solution from PoC and alignment with the Roche Security Standard.",
    },
    highlights: {
      fr: [
        "Design de la solution META1 à partir du PoC existant",
        "Amélioration de la sécurité et alignement avec le Roche Security Standard",
        "Design de la chaîne CI/CD de la solution",
      ],
      en: [
        "Design of the META1 solution from the existing PoC",
        "Security improvements and alignment with the Roche Security Standard",
        "Design of the solution's CI/CD chain",
      ],
    },
    stack: [
      "Route53",
      "CloudFront",
      "Cognito",
      "Amplify",
      "AppSync",
      "CMK/KMS",
      "S3",
      "IAM",
      "API Gateway",
      "DynamoDB",
      "Elasticsearch",
      "CodePipeline",
      "Sumologic",
      "Dome9",
    ],
  },
  {
    id: "axa",
    client: "AXA Group Operations",
    role: { fr: "AWS Security Architect", en: "AWS Security Architect" },
    period: { fr: "Octobre 2020 — Décembre 2020", en: "October 2020 — December 2020" },
    start: "2020-10",
    location: "Paris",
    freelance: true,
    summary: {
      fr: "Évaluation des risques des services et applications AXA hébergés sur AWS.",
      en: "Risk assessment of AXA services and applications hosted on AWS.",
    },
    highlights: {
      fr: [
        "Risk assessments des services et applications AXA hébergés sur AWS",
        "Implémentation d'un Assurance Plan de la AWS Foundation pour le groupe",
      ],
      en: [
        "Risk assessments of AXA services and applications hosted on AWS",
        "Implementation of an AWS Foundation Assurance Plan for the group",
      ],
    },
    stack: ["AWS", "Risk Assessment", "Compliance"],
  },
  {
    id: "airbus-skywise-dx",
    client: "Airbus",
    role: {
      fr: "AWS Solution Architect — Skywise DX/DA",
      en: "AWS Solution Architect — Skywise DX/DA",
    },
    period: { fr: "Avril 2019 — Avril 2020", en: "April 2019 — April 2020" },
    start: "2019-04",
    location: "Blagnac",
    freelance: true,
    summary: {
      fr: "Technical Leader sur la Skywise Developer Experience, avec la conception d'un Massive Data Extractor pour les compagnies aériennes.",
      en: "Technical Leader on Skywise Developer Experience, designing a Massive Data Extractor for airlines.",
    },
    highlights: {
      fr: [
        "Rôle de Technical Leader sur le périmètre DX/DA",
        "Définition, design, implémentation et déploiement d'un Massive Data Extractor pour les airlines",
        "Consultation et support de l'équipe DX sur les aspects architecturaux",
      ],
      en: [
        "Technical Leader role on the DX/DA scope",
        "Definition, design, implementation and deployment of a Massive Data Extractor for airlines",
        "Architecture consulting and support for the DX team",
      ],
    },
    stack: [
      "Lambda",
      "ECS",
      "S3",
      "SNS",
      "IAM",
      "KMS",
      "Step Functions",
      "CloudFront",
      "CloudFormation",
      "MobileSSO",
      "OneLogin",
      "Mulesoft",
      "Salesforce",
      "Foundry",
      "Jenkins",
      "SonarQube",
    ],
  },
  {
    id: "navblue",
    client: "NavBlue",
    role: { fr: "AWS Solution Architect", en: "AWS Solution Architect" },
    period: { fr: "Décembre 2018 — Mars 2019", en: "December 2018 — March 2019" },
    start: "2018-12",
    location: "Blagnac",
    freelance: true,
    summary: {
      fr: "Définition des solutions Ops dédiées et de l'architecture EKS pour les applications NavBlue.",
      en: "Definition of dedicated Ops solutions and EKS architecture for NavBlue applications.",
    },
    highlights: {
      fr: [
        "Définition des solutions Ops dédiées et PoC de validation",
        "Architecture et infrastructure AWS EKS (Kubernetes) pour les applications NavBlue",
        "Infrastructure as Code pour automatiser chaque nouvel environnement EKS avec son outillage",
        "Support de l'équipe Ops pour l'adoption et rédaction des documents d'architecture",
      ],
      en: [
        "Definition of dedicated Ops solutions and validation PoCs",
        "AWS EKS (Kubernetes) architecture and infrastructure for NavBlue applications",
        "Infrastructure as Code to automate every new EKS environment and its tooling",
        "Ops team enablement and architecture documentation",
      ],
    },
    stack: [
      "Terraform",
      "EKS",
      "EC2",
      "VPC",
      "RDS",
      "Lambda",
      "Route53",
      "ELB",
      "Kubernetes",
      "Grafana",
      "Prometheus",
      "Jenkins",
    ],
  },
  {
    id: "airbus-data-factory",
    client: "Airbus",
    role: { fr: "Solution Architect — Data Factory", en: "Solution Architect — Data Factory" },
    period: { fr: "Octobre 2018 — Mars 2019", en: "October 2018 — March 2019" },
    start: "2018-10",
    location: "Blagnac",
    freelance: true,
    summary: {
      fr: "Solution de monitoring de l'ingestion de données legacy dans Skywise.",
      en: "Monitoring solution for legacy data ingestion into Skywise.",
    },
    highlights: {
      fr: [
        "Définition et design de la solution de monitoring",
        "Implémentation de dashboards Splunk pour la data health des pipelines, en historique et en temps réel",
      ],
      en: [
        "Definition and design of the monitoring solution",
        "Splunk dashboards for pipeline data health, both historical and real-time",
      ],
    },
    stack: ["Foundry", "Splunk", "Legacy applications"],
  },
  {
    id: "afklm",
    client: "Air France-KLM",
    role: { fr: "Cloud Security Architect", en: "Cloud Security Architect" },
    period: { fr: "Janvier 2018 — Juillet 2018", en: "January 2018 — July 2018" },
    start: "2018-01",
    location: "Toulouse",
    freelance: true,
    summary: {
      fr: "Définition des security best practices du cloud hybride AWS/Azure et de l'architecture cible.",
      en: "Definition of hybrid AWS/Azure cloud security best practices and target architecture.",
    },
    highlights: {
      fr: [
        "Promotion et support des stratégies et concepts cloud auprès des équipes",
        "Définition des Security Best Practices pour le cloud hybride AWS et Azure",
        "Proposition de designs de l'architecture cible alignés sur les compliances AF/KLM",
        "Définition de security design patterns et implémentation de la solution retenue",
        "Continuous service transition avec des équipes 24×7",
        "Support des RFP IDaaS et CASB selon les security best practices",
      ],
      en: [
        "Promotion and support of cloud strategies and concepts across teams",
        "Definition of Security Best Practices for the hybrid AWS and Azure cloud",
        "Target architecture designs aligned with AF/KLM compliance requirements",
        "Definition of security design patterns and implementation of the selected solution",
        "Continuous service transition with 24×7 teams",
        "Support for IDaaS and CASB RFPs following security best practices",
      ],
    },
    stack: ["AWS", "Azure", "Hybrid Cloud", "IDaaS", "CASB"],
  },
  {
    id: "airbus-physical-design",
    client: "Airbus",
    role: {
      fr: "IT Architect — Physical Design Activities",
      en: "IT Architect — Physical Design Activities",
    },
    period: { fr: "Juillet 2012 — Décembre 2017", en: "July 2012 — December 2017" },
    start: "2012-07",
    location: "Saint-Martin du Touch",
    freelance: true,
    featured: true,
    summary: {
      fr: "Cinq ans et demi sur le design physique des nouvelles solutions et infrastructures Airbus, aligné sur l'architecture fonctionnelle et les SLA métier.",
      en: "Five and a half years designing the physical layer of new Airbus solutions and infrastructure, aligned with functional architecture and business SLAs.",
    },
    highlights: {
      fr: [
        "Leadership du technical design des nouvelles solutions selon l'architecture fonctionnelle et les Business Service Level Requirements",
        "Alignement avec les middlewares standards Airbus (VAX/VMS, MS SQL, DB2, AIX, Websphere, Tomcat, Oracle, Windows Server)",
        "Alignement avec la security policy et les contraintes opérationnelles",
        "Définition des composants d'infrastructure (IaaS, PaaS, storage, network) selon les standards Airbus",
        "Design d'infrastructures haute disponibilité, animation de workshops d'architecture technique",
        "Estimation des coûts de déploiement (hardware, software, operations, design) et évaluation de scénarios d'architecture avec analyse pros/cons",
      ],
      en: [
        "Led the technical design of new solutions per functional architecture and Business Service Level Requirements",
        "Alignment with Airbus standard middleware (VAX/VMS, MS SQL, DB2, AIX, Websphere, Tomcat, Oracle, Windows Server)",
        "Alignment with security policy and operational constraints",
        "Definition of infrastructure components (IaaS, PaaS, storage, network) per Airbus standards",
        "High availability infrastructure design, technical architecture workshops",
        "Deployment cost estimation (hardware, software, operations, design) and architecture scenario evaluation with pros/cons analysis",
      ],
    },
    stack: [
      "J2EE",
      ".NET",
      "LDAP",
      "Unix/Solaris",
      "Websphere",
      "Tomcat",
      "Siteminder",
      "Kerberos",
      "Windchill",
      "AIX",
      "VMS",
      "ESX",
      "Active Directory",
      "Grid Computing",
    ],
  },
  {
    id: "infotel",
    client: "Infotel",
    role: { fr: "Expert Java/J2EE", en: "Java/J2EE Expert" },
    period: { fr: "Octobre 2011 — Avril 2012", en: "October 2011 — April 2012" },
    start: "2011-10",
    location: "Blagnac",
    freelance: true,
    summary: {
      fr: "Support technique du projet ADOC Manager V3.1 pour Airbus.",
      en: "Technical support for the ADOC Manager V3.1 project for Airbus.",
    },
    highlights: {
      fr: [
        "Analyse et design d'un prototype d'import/export en masse de documents SGML",
        "Analyse de l'architecture logicielle pour le handover de l'application",
        "Design d'évolutions, spécifications techniques et mise à jour du système d'indexation",
        "Déploiement des environnements de développement et de production",
      ],
      en: [
        "Analysis and design of a bulk SGML document import/export prototype",
        "Software architecture analysis for the application handover",
        "Evolution design, technical specifications and indexing system update",
        "Deployment of development and production environments",
      ],
    },
    stack: [
      "Java 6",
      "J2EE 5",
      "Hibernate",
      "JBoss",
      "Spring 2.0",
      "Tomcat 5.5",
      "Oracle 11g",
      "Linux RH",
      "XML/SGML",
      "Maven",
      "ApacheMQ",
    ],
  },
  {
    id: "airbus-corporate",
    client: "Airbus",
    role: {
      fr: "IT Architect — Corporate Functions & Security",
      en: "IT Architect — Corporate Functions & Security",
    },
    period: { fr: "Avril 2011 — Décembre 2011", en: "April 2011 — December 2011" },
    start: "2011-04",
    location: "Blagnac",
    freelance: true,
    summary: {
      fr: "Architecture d'infrastructure pour les Corporate Functions et les Security Solutions.",
      en: "Infrastructure architecture for Corporate Functions and Security Solutions.",
    },
    highlights: {
      fr: [
        "Définition de l'architecture d'infrastructure pour les Corporate Functions et Security Solutions",
        "Technical design des nouvelles solutions selon l'architecture fonctionnelle et les SLA métier",
        "Définition des composants d'infrastructure (server, storage, network) selon les standards Airbus",
        "Workshops d'architecture technique, estimation des coûts et évaluation de scénarios",
      ],
      en: [
        "Infrastructure architecture definition for Corporate Functions and Security Solutions",
        "Technical design of new solutions per functional architecture and business SLAs",
        "Definition of infrastructure components (server, storage, network) per Airbus standards",
        "Technical architecture workshops, cost estimation and scenario evaluation",
      ],
    },
    stack: [
      "J2EE",
      ".NET",
      "LDAP",
      "Unix/Solaris",
      "Websphere 6",
      "Siteminder",
      "Kerberos",
      "Windchill",
      "Active Directory",
    ],
  },
  {
    id: "airbus-france",
    client: "Airbus France",
    role: { fr: "IT Architect", en: "IT Architect" },
    period: { fr: "Novembre 2007 — Décembre 2010", en: "November 2007 — December 2010" },
    start: "2007-11",
    location: "Saint-Martin du Touch",
    freelance: true,
    summary: {
      fr: "Architecte Functional Design Activities pour les projets des différents departments engineering.",
      en: "Functional Design Activities architect for projects across engineering departments.",
    },
    highlights: {
      fr: [
        "Validation de l'architecture des solutions applicatives des projets engineering",
        "Garantie de la cohérence et de la conformité avec l'infrastructure standard, les règles d'intégration et la sécurité Airbus",
        "Consultation et support des projets en phase de design, animation de workshops d'architecture technique",
        "Établissement de modèles techniques, rédaction et validation des records d'architecture",
        "Support sur les RFI et RFP en phase préliminaire",
      ],
      en: [
        "Validation of application solution architecture across engineering projects",
        "Ensured consistency and compliance with Airbus standard infrastructure, integration rules and security",
        "Design-phase consulting and support, technical architecture workshops",
        "Technical models, drafting and validation of architecture records",
        "RFI and RFP support during the preliminary phase",
      ],
    },
    stack: [
      "J2EE 1.4/5",
      "Hibernate",
      "Struts",
      "Spring",
      ".NET",
      "LDAP",
      "Unix/Solaris",
      "Tomcat",
      "Websphere 6",
      "Siteminder",
      "Alfresco",
    ],
  },
  {
    id: "orange",
    client: "Orange",
    role: { fr: "Technical Manager / Architect", en: "Technical Manager / Architect" },
    period: { fr: "Juin 2006 — Octobre 2007", en: "June 2006 — October 2007" },
    start: "2006-06",
    location: "Blagnac",
    summary: {
      fr: "Exploitation technique de l'application E-Technician : front office PDA/WAP et back office web.",
      en: "Technical operations of the E-Technician application: PDA/WAP front office and web back office.",
    },
    highlights: {
      fr: [
        "Point focal technique de l'application, gestion des opérations, monitoring et bug tracking",
        "Budgeting et développement des mises à jour : batchs, composants Java (Servlet, JSP), correctifs, versioning",
        "Organisation des environnements techniques et opérationnels",
        "Rédaction et validation des records d'architecture, naming handbooks, métrologie et spécifications de flux",
      ],
      en: [
        "Technical focal point for the application, operations management, monitoring and bug tracking",
        "Budgeting and development of updates: batches, Java components (Servlet, JSP), bug fixing, versioning",
        "Organization of technical and operational environments",
        "Drafting and validation of architecture records, naming handbooks, metrology and flow specifications",
      ],
    },
    stack: [
      "J2EE",
      "JSP",
      "XML/XSL",
      "AXIS",
      "WAP",
      "Web Services",
      "Jolt/Tuxedo",
      "Oracle 9i",
      "JMS",
      "MQ-Series",
      "Apache",
    ],
  },
  {
    id: "gfi",
    client: "GFI Informatique",
    role: { fr: "IT Architect", en: "IT Architect" },
    period: { fr: "2006 — Décembre 2009", en: "2006 — December 2009" },
    start: "2006-01",
    location: "Toulouse",
    summary: {
      fr: "Design des plateformes pour les projets de l'agence de Toulouse.",
      en: "Platform design for the Toulouse agency's projects.",
    },
    highlights: {
      fr: [
        "Design des plateformes pour les projets de l'agence",
        "Support technique transverse sur les projets",
        "Création et management du département technique de l'agence",
      ],
      en: [
        "Platform design for the agency's projects",
        "Cross-project technical support",
        "Creation and management of the agency's technical department",
      ],
    },
    stack: ["J2EE", "PHP", "LemonLDAP", "Oracle"],
  },
  {
    id: "la-poste",
    client: "La Poste",
    role: { fr: "Expert technique", en: "Technical Expert" },
    period: { fr: "Août 2005 — Mai 2006", en: "August 2005 — May 2006" },
    start: "2005-08",
    location: "Montpellier",
    summary: {
      fr: "Étude d'interfaçage entre Habilinet et le portail W@C (Vignette).",
      en: "Interfacing study between Habilinet and the W@C portal (Vignette).",
    },
    highlights: {
      fr: [
        "Étude et document technique des solutions d'interfaçage WAC / Habilinet suite à la migration Vignette",
        "Prototypes, tests unitaires, d'intégration et de charge",
        "Étude des enjeux de sécurité entre Habilinet et le portail W@C",
        "Mise en production d'Habilinet 2.1.0 : design, architecture, manuels d'installation, nouveaux modules",
      ],
      en: [
        "Study and technical document on WAC / Habilinet interfacing solutions after the Vignette migration",
        "Prototypes, unit, integration and workload tests",
        "Security assessment between Habilinet and the W@C portal",
        "Habilinet 2.1.0 release: design, architecture, installation manuals, new modules",
      ],
    },
    stack: [
      "ASP.NET",
      "COM+",
      "VB6",
      "C#",
      ".NET 1.2",
      "J2EE 1.4",
      "Portlet (JSR 168)",
      "SOAP",
      "SQL Server",
      "Vignette 7.2",
      "XML/XSL",
    ],
  },
  {
    id: "brl-tpm",
    client: "BRL",
    role: { fr: "Technical Project Manager", en: "Technical Project Manager" },
    period: { fr: "Juin 2005 — Août 2005", en: "June 2005 — August 2005" },
    start: "2005-06",
    location: "Nîmes",
    summary: {
      fr: "Intégration du système d'information BRL (Borneo).",
      en: "Integration of the BRL information system (Borneo).",
    },
    highlights: {
      fr: [
        "Intégration du système d'information Borneo",
        "Suivi des opérations, implémentation des mises à jour et bug tracking",
      ],
      en: [
        "Integration of the Borneo information system",
        "Operations monitoring, update implementation and bug tracking",
      ],
    },
    stack: ["Unix", "Tomcat 5", "Oracle 9i", "JSP", "J2EE 1.4", "Mantis"],
  },
  {
    id: "brl-swe",
    client: "BRL",
    role: { fr: "Software Engineer", en: "Software Engineer" },
    period: { fr: "Décembre 2004 — Mai 2005", en: "December 2004 — May 2005" },
    start: "2004-12",
    location: "Montpellier",
    summary: {
      fr: "Design et développement du système d'information BRL (Borneo).",
      en: "Design and development of the BRL information system (Borneo).",
    },
    highlights: {
      fr: [
        "Design et développement des composants, tests et intégration",
        "Intégration de Quartz (OpenSymphony) et rédaction du manuel d'intégration",
      ],
      en: [
        "Component design and development, testing and integration",
        "Quartz (OpenSymphony) integration and integration manual",
      ],
    },
    stack: ["Unix", "Tomcat 5", "Oracle 9i", "JSP", "J2EE 1.4", "JavaScript"],
  },
  {
    id: "generali",
    client: "Generali",
    role: { fr: "Developer Engineer", en: "Developer Engineer" },
    period: { fr: "Avril 2004 — Mai 2004", en: "April 2004 — May 2004" },
    start: "2004-04",
    location: "Saint-Denis",
    summary: {
      fr: "Outils de support pour l'administration WebSphere 5.1.",
      en: "Support tooling for WebSphere 5.1 administration.",
    },
    highlights: {
      fr: [
        "Design et développement des outils de support pour l'administration WebSphere 5.1",
        "Wrapper scripts de composants Java, tests unitaires et d'intégration",
      ],
      en: [
        "Design and development of support tools for WebSphere 5.1 administration",
        "Java component wrapper scripts, unit and integration testing",
      ],
    },
    stack: ["AIX", "Shell Script", "JACL", "J2EE 1.4", "Log4J", "Websphere 5.1"],
  },
];

export const featuredExperiences = experiences.filter((experience) => experience.featured);

export const clientCount = new Set(experiences.map((experience) => experience.client)).size;
